### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#10]
Is the Windows portion of the README still valid?
I removed the references to `NT` which seemed most anachronic,
but can someone please verify that the described process still works?
Is `Visual C++ 6.0` still relevant? Do we care about building on Windows
or should we just get rid of that?

**Comment by mcd500** [comment]
The people who might use rtptools on Windows might not large, that being said, having able to build on any type of different platform like Windows is really helpful to finding bugs or breakage between Unix like OSs or 32bits and 64bits system.
I used to check both rtptools building and testing on both Windows 2000, Linux, and Solaris at least.  And I remember I was testing it on Win98 too.

The reason of name convention of NT is because when the time of rtptools was developed, WIndows had two series. One was 95/98/Me which behaved differently with limited POSIX compatibility (which was built on top of MS-DOS). The other was Win NT and starting from poring from Unix on NT was easier which became 2000/XP/Vista/7/8*/10. The porting to NT behaved much similar as a POSIX compatible multi-task operating system.
I agree that the name NT is obsolete and we could change the name of NT any time in the future.

The current Visual Studio 2017 is still compatible of building Visual C++ 6.0 (I need to double check with rtptools), and I think it is fine leaving it.
Probably good to add the instruction of how to build it with recent Visual Studio when we have time.

**Comment by mcd500** [comment]
I am planning skipping supporting build on Windows for the next 1.22 release.

I will take care of making them able to build on Windows in the future releases.

**Comment by janstary** [comment]
See https://github.com/columbia-irt/rtptools/pull/15 for removing win support.

**Comment by mcd500** [comment]
#15 removes  all the files for the build on windows. Removing them entirely would make it really difficult when we try to fix the build on windows. Leaving those file have no harm for the releasing and development.

**Comment by janstary** [comment]
We know the win code does not work, it does not even compile.
It is broken, and apparently has been rotting for years.
So what do we do - ship it? No.

It's not at all difficult to get it back - just pull out an old commit.

**Comment by janstary** [comment]
A clean PR is prepared in https://github.com/columbia-irt/rtptools/pull/26 - please don't let the broken, nonworking code into the upcomming release.

**Comment by mcd500** [comment]
Thanks for the https://github.com/columbia-irt/rtptools/pull/26
I pushed it to the branch no-win for the maintainability.
https://github.com/columbia-irt/rtptools/tree/no-win

**Comment by janstary** [comment]
The broken windows code still lives on in master, so this is not really closed ...
