### ISSUE TITLE
RTP dissector for tcpdump

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#54]
The ubiquituous tcpdump traffic analyzer analyzes packets on the TCP/UDP -> IP -> ETH level,
but also has dissectors for the insides of some chosen protocols (such as DNS).
As the RTP Tools contain detailed knowledge of the RTP protocol (obviously),
it might be beneficial to extract some of that knowledge to create
a RTP dissector to be used in tcpdump and wireshark.

I have not looked yet at how much of that they do now.

**Comment by njh** [comment]
Here is a Wireshark capture of `rtpplay -f bark.rtp 127.0.0.1/5004`:

<img width="1024" alt="bark-rtp-wireshark" src="https://user-images.githubusercontent.com/38734/37874682-c5a39d40-302b-11e8-827b-7e03d04aff3f.png">

Note that I had to manually associate port 5004 with RTP, so that it decoded the contents of the UDP packets.

**Comment by janstary** [comment]
Thanks. So they probably do a lot of that already.
